[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "tpope/vim-commentary"

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "junegunn/fzf"
build = './install --all'

[[plugins]]
repo = "junegunn/fzf.vim"

[[plugins]]
repo = "fatih/vim-go"

[[plugins]]
repo = "pangloss/vim-javascript"

[[plugins]]
repo = "sheerun/vim-polyglot"

[[plugins]]
repo = "altercation/vim-colors-solarized"

[[plugins]]
repo = "Yggdroot/indentLine"

